[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]
aptsPackages = ["default-mysql-client"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --working-dir=backend"]

[phases.build]
cmds = [
  "php backend/artisan config:cache",
  "php backend/artisan route:cache",
  "php backend/artisan migrate --force"
]

[start]
cmd = "php backend/artisan serve --host=0.0.0.0 --port=$PORT"
